const GET_MY_CONTENTS = "GET_MY_CONTENTS";
const GET_IMPORTANT_CONTENTS = "GET_IMPORTANT_CONTENTS";
const GET_FAVORITE_CONTENTS = "GET_FAVORITE_CONTENTS";
const GET_SHARED_CONTENTS = "GET_SHARED_CONTENTS";
const GET_DEPARTMENT_CONTENTS = "GET_DEPARTMENT_CONTENTS";
const GET_TRASH_CONTENTS = "GET_TRASH_CONTENTS";
const GET_CONTENTS_FROM_PATH = "GET_CONTENTS_FROM_PATH";
const CHANGE_FAVORITE = "ADD_FAVORITE";
const CHANGE_IMPORTANT = "CHANGE_IMPORTANT";

export {
  GET_MY_CONTENTS,
  GET_IMPORTANT_CONTENTS,
  GET_FAVORITE_CONTENTS,
  GET_SHARED_CONTENTS,
  GET_DEPARTMENT_CONTENTS,
  GET_TRASH_CONTENTS,
  GET_CONTENTS_FROM_PATH,
  CHANGE_FAVORITE,
  CHANGE_IMPORTANT,
};
