export const GET_DIRECTORIES = "GET_DIRECTORIES";
export const DELETE_DIRECTORY = "DELETE_DIRECTORY";

export const BEGIN_UPDATE_DIRECTORY = "BEGIN_UPDATE_DIRECTORY";
export const UPDATE_DIRECTORY_SUCCESS = "UPDATE_DIRECTORY_SUCCESS";
export const UPDATE_DIRECTORY_FAILURE = "UPDATE_DIRECTORY_FAILURE";
