export const UPDATE_CURRENT_PAGE = "UPDATE_CURRENT_PAGE";
export const UPDATE_TOTAL_PAGES = "UPDATE_TOTAL_PAGES";
export const UPDATE_PAGE_LIMIT = "UPDATE_PAGE_LIMIT";
export const UPDATE_TOTAL_RECORDS = "UPDATE_TOTAL_RECORDS";
export const UPDATE_PAGE_NEIGHBOURS = "UPDATE_PAGE_NEIGHBOURS";
